### ISSUE TITLE
bruh, I think your discord account got pwned.

### ISSUE THREAD

**Issue by sirocyl** [Sylveon76/Mewdeko#106]
Might wanna go ahead and like, change your passwords from a computer that hasn't been compromised.

Products affected:
- Mewdeko's Clubhouse discord server
- Sylveon76 Discord account
- Possibly other accounts, if they've moved across your stuff.

Yikes.

**Comment by Sylveon76** [comment]
Nope, only my discord

**Comment by sirocyl** [comment]
Oh, okay. Because you were sending spam messages from your discord account there, like someone hacked it. Carry on then
